### ISSUE TITLE
Remove function

### ISSUE THREAD

**Issue by conorpaschenko** [grahamwren/cs4500-assignment_1-part2#12]
In the comment for remove it says the value at the given key would be removed. Shouldn't the key also be removed as well?

**Comment by grahamwren** [comment]
Maps are a keyed representation of the values in the `Map`, as such, there is no way for a key to exist without an associated value.

Even in the case of a `nullptr` value, that would only occur through `Map::set(new String("hello"), nullptr)`.

Removing the value in a `Map`, as opposed to updating a value to `nullptr`, removes the entry from the `Map` and this includes the key.
