### ISSUE TITLE
Hash contract

### ISSUE THREAD

**Issue by kylesferrazza** [grahamwren/cs4500-assignment_1-part2#14]
You've got the wrong idea for `hash`, and it shows in the tests.
If two objects are `equal`, they have to have the same hash.
If they are different, the hashes **do not** need to be different.
This test is therefore incorrect:
https://github.com/grahamwren/cs4500-assignment_1-part2/blob/5900dcdabbbf062703141600684036fa5020fd52/test-map.cpp#L215-L216

**Comment by jagen31** [comment]
Fixed.
