### ISSUE TITLE
incorrect remove test

### ISSUE THREAD

**Issue by kylesferrazza** [grahamwren/cs4500-assignment_1-part2#15]
In the following snippet:
https://github.com/grahamwren/cs4500-assignment_1-part2/blob/5900dcdabbbf062703141600684036fa5020fd52/test-map.cpp#L257-L266

The value corresponding to `Hello` is removed, but the one corresponding to `Design` is not, and you test that it is.

This can be fixed by adding
```cpp
theMap->remove(new String("Design"));
```

just after line 258.

**Comment by jagen31** [comment]
Fixed. The intent was to give `sameKey2` the same value as `key2`, so I changed "World" to "Design".
