### ISSUE TITLE
Test Corrections

### ISSUE THREAD

**Issue by jsxtam** [grahamwren/cs4500-assignment_1-part2#17]
In your tests (`test-map.cpp`) you allocate memory but don't free it at the end of your tests. In addition, you're only using `String` to `String` mappings for your tests. While this may cover the `String` to `Object` maps, you may want to add specific tests for this use case.

## In Summary

* Add `delete`s  every time you allocate memory for a variable
* Add some tests to cover `String` to `Object` maps

Thanks!

**Comment by jagen31** [comment]
1. Memory which is allocated in tests and not in a loop doesn't need to be freed, the OS will reclaim it when the tests finish.

2. We are testing the behaviors of the map, which doesn't rely on any special properties of strings.  Testing with different types of objects would be redundant.

**Comment by grahamwren** [comment]
We will not be implementing this based on discussions in class on freeing memory in tests and on the responsibility for `String`/`Object` tests.

**Comment by jjones-99** [comment]
Okay, that's totally fine. ✌️

Our lectures seem to be completely different than Jan's and don't really help with the homework, so we never know this stuff unless something about it appears on Piazza.

Just to clarify, is there any reason not to do these things—other than 'more typing'?

**Comment by grahamwren** [comment]
No specific reason other than it being redundant. All of the memory will be recollected by the OS as soon as the process exists so since we know this main file is run straight through and then exits, the memory would be returned to the OS very soon after you have freed it. If we were dealing with a larger test suite or framework where we don't have as much control over how and when the tests are run it would be more important to clean up the memory we use but in this case, it won't make a difference.

**Comment by grahamwren** [comment]
Hmm or were you asking about the `Map<String, Object>` tests?

In that case, given that our interface is sufficiently tested to work with `Object` and that `String extends Object`, whether or not a `Map` accepts `String` keys or values is a language feature and I don't seem much value in testing language features, similar to how it would be bad practice to test behavior implemented by an external library.

Also, our interface for `Object` is abstract so I don't think we have any tests which actually use any type of `Object` other than `String`.

**Comment by jjones-99** [comment]
Ah, okay. That all makes sense, thanks!
