### ISSUE TITLE
No way to retrieve a String value

### ISSUE THREAD

**Issue by kylesferrazza** [grahamwren/cs4500-assignment_1-part2#3]
At present, `Object *get(Object *key)` is the only way to retrieve a value from the map.

If I know my `Map` only has `String` values, I may want to `get` a `String *` so I don't have to cast every result of every call to `get`.

One way this could be accomplished is a secondary `Map` class specifically for `String` values, with a method like: `String *get(Object *key)`. While not ideal, this seems to be the best we can do with CwC (no templates/generics).

**Comment by bendavp** [comment]
Hey Kyle,

Just to let you know, I submitted pull request #6 to rectify this issue by creating another class called `StringMap`. Hope this resolves your issue!

**Comment by kylesferrazza** [comment]
fixed in #6
