### ISSUE TITLE
Tests don't instantiate Map.

### ISSUE THREAD

**Issue by kylesferrazza** [grahamwren/cs4500-assignment_1-part2#5]
Tests are littered with `...` where calls to the `Map` constructor should live.

Examples:

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L10

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L29

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L54

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L68

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L80

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L102

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L117

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L137

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L162

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L185-L186

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/8ecd865e2d4d921aa1f9638f05336acf3cb890bb/test-map.cpp#L222

It is expected that the spec specifies some constructor for `Map`.

Please add a constructor to the spec, and update the tests accordingly to call it.

**Comment by grahamwren** [comment]
Fixed by https://github.com/grahamwren/cs4500-assignment_1-part2/commit/4acbcd18ec1825596ae3dc0924379407beaa238a
