### ISSUE TITLE
Add a String(const char*) constructor.

### ISSUE THREAD

**Issue by jjones-99** [grahamwren/cs4500-assignment_1-part2#8]
The only `String` constructor offered in the spec is the default constructor but `test-map.cpp` uses a `String(const char*)` constructor (e.g., `String *key = new String("Hello");`)

While we can add this to the implementation, I think everything appearing in the test suite should be considered public, so it should all also appear in the spec. (Plus, if anything, `String(const char*)` is the only constructor most users would need to worry about.)

**Comment by grahamwren** [comment]
https://github.com/grahamwren/cs4500-assignment_1-part2/issues/9#issuecomment-579571504
