### ISSUE TITLE
test-map.cpp: get() returns an Object*, not a String*

### ISSUE THREAD

**Issue by jjones-99** [grahamwren/cs4500-assignment_1-part2#9]
In the given `test-map.cpp` file, lines like `String *str = theMap->get(key);` appear. However, these lines won't compile because `get()` returns an `Object*`, not a `String*`. We can think of two fixes:

- Add casts into `test-map.cpp` wherever you want to pull a `String` out of the `Map`. (e.g, `String *str = dynamic_cast<String*>(theMap->get(key));`
- Design a spec like `StringMap` that does all of that casting for you. (This has been discussed (#7) but cancelled.)

### Our Thoughts

While we agree that the `StringMap` class isn't a 'requirement', we do think that it would be a very useful abstraction (concretization?) for the user. And if we think about designing specs, it seems that they should be designed in a way that reduces friction with the user as much as possible.

For a reference to a higher authority, Jan mentioned in [Piazza @331](https://piazza.com/class/k51bluky59n2jr?cid=331) that "...I do believe that from an API it is clearly better to avoid the cast (because it is unchecked and you could get it wrong)," and seems to imply that reducing the amount you force a user to cast after writing a function is a 'better' design choice.

**If you still want to leave `StringMap` out of the spec, that's still perfectly fine as far as requirements go: we just wanted to give our two cents. Regardless, `test-map.cpp` should still be fixed to 'compile' with whatever design choices you make.**

**Comment by grahamwren** [comment]
Sorry about that, I thought we had compiled these already.
Fixed by https://github.com/grahamwren/cs4500-assignment_1-part2/commit/5900dcdabbbf062703141600684036fa5020fd52
